### ISSUE TITLE
Google calendar iframe not rendering

### ISSUE THREAD

**Issue by NeilCFord** [chrisanthropic/slim-pickins-jekyll-theme#10]
The theme is working wonderfully, except that I am trying to embed a Google Calendar in to a page and it is not rendering properly. I've searched around and it appears one issue may be how kramdown handles iframes, so I switched to rdiscount to see if that would help, no joy.

The page source is as follows:
    ---
    layout: page
    title: Calendar
    permalink: /calendar/
    ---
    {% raw %}
    ``<iframe src="https://calendar.google.com/calendar/embed?src=ihh86udbrsmle45ckb8m2lc8e0%40group.calendar.google.com&ctz=Europe/London" style="border: 0" width="800" height="600" frameborder="0" scrolling="no">&nbsp;</iframe>``
    {% endraw %}''

The page is currently live, so I can't link to it. I can make it so if that helps.

Really just looking for some pointers as to might what be wrong.

Neil.

**Comment by NeilCFord** [comment]
Please ignore. Turned out to be something unrelated to the theme. I will go and sit quietly in the corner now.

Neil.

**Comment by clarkatron** [comment]
What was the issue?  I am having a problem with iframes and my google calendar right now.

**Comment by NeilCFord** [comment]
In my case it was a tracking cookie blocker. In order for the embedded calendar to load I need to allow the google.com cookies. I discovered this by loading the page in a vanilla browser and then looking at my browser plugins to figure out the cause.
