### ISSUE TITLE
Installation error - invalid switch?

### ISSUE THREAD

**Issue by shevett** [chrisanthropic/slim-pickins-jekyll-theme#2]
I'm having a problem doing the installation.   Ruby version:
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
This is on a mac:

```
Daves-MacBook-Pro:slim-pickins-jekyll-theme dave shevett$ bundle install --binstubs --path=vendor
Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Installing rake 10.4.2
Installing Platform 0.4.0
Installing open4 1.3.4
Installing POpen4 0.1.4
Installing blankslate 2.1.2.4

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby: invalid switch in RUBYOPT: -s (RuntimeError)


Gem files will remain installed in /Users/dave shevett/Documents/v2usdra.org/slim-pickins-jekyll-theme/vendor/ruby/2.0.0/gems/hitimes-1.2.2 for inspection.
Results logged to /Users/dave shevett/Documents/v2usdra.org/slim-pickins-jekyll-theme/vendor/ruby/2.0.0/gems/hitimes-1.2.2/ext/hitimes/c/gem_make.out
An error occurred while installing hitimes (1.2.2), and Bundler cannot continue.
Make sure that `gem install hitimes -v '1.2.2'` succeeds before bundling.
Daves-MacBook-Pro:slim-pickins-jekyll-theme dave shevett$
```

**Comment by chrisanthropic** [comment]
I'm on a linux box here, but it looks like there were some issues recently with hitimes and OSX - https://github.com/copiousfreetime/hitimes/issues/28 (among others)

Updating to Ruby 2.1.1 seems to fix the issue for most people.

**Comment by shevett** [comment]
Not sure if it's hitimes giving the hassle here.  When I run it manually, i get a warning, but I think it's installed:

```
Building native extensions.  This could take a while...
Successfully installed hitimes-1.2.2
Parsing documentation for hitimes-1.2.2
unable to convert "\xCA" from ASCII-8BIT to UTF-8 for lib/hitimes/2.0/hitimes.bundle, skipping
1 gem installed
```

**Comment by chrisanthropic** [comment]
You can try running `bundle install` and install the gems universally instead of `bundle install --binstubs --path=vendor` the path could be the issue here.

**Comment by shevett** [comment]
Nope.  Same problem :(

**Comment by chrisanthropic** [comment]
The errors still make it look like a hitimes issue to me, in fact this one popped up again recently `unable to convert "\xCA" from ASCII-8BIT to UTF-8 for lib/hitimes/2.0/hitimes.bundle, skipping` - and was apparently fixed by running `gem install --verbose hitimes` or `bundle update`.

If that doesn't fix it, you'll need to troubleshoot your jekyll/ruby installation - here's a link that may help:
http://hasset.github.io/it/2015/01/01/issue-of-ruby-while-installing-jekyll/
