### ISSUE TITLE
Ignore image_optim_cache.yml on Git

### ISSUE THREAD

**Issue by ruflin** [chrisanthropic/slim-pickins-jekyll-theme#4]
The file `images/image_optim_cache.yml` is automatically regenerated when need. Does this have to be included on Git or could it be added to .gitignore?

**Comment by chrisanthropic** [comment]
It can safely be added to .gitignore since it is regenerated as needed.

**Comment by ruflin** [comment]
Ok, I will open a pull request so we have it directly in the repository.

**Comment by ruflin** [comment]
See https://github.com/ruflin/slim-pickins-jekyll-theme/commit/4c39332cf5059cf27910c11a55c3dfd507dbbfbf
