### ISSUE TITLE
Kitchen Sink Page

### ISSUE THREAD

**Issue by captaincoffee** [chrisanthropic/slim-pickins-jekyll-theme#9]
Nice work. A Kitchen Sink Page is always appreciated in a Foundation Theme to test that everything is installed correctly.

**Comment by chrisanthropic** [comment]
Thanks, but everything isn't installed correctly since I use very minimal amounts of Foundation (grid & visibility classes). I suppose I could set up a page demonstrating those two features, but that's all that's used by default.
